project_id = "circle"

[api]
enabled = true
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
